version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: glavingo-nginx
    hostname: nginx.${DOMAIN_NAME}
    domainname: ${DOMAIN_NAME}
    volumes:
      - ./:/app
      - ${NGINX_CONF_FOLDER}:/etc/nginx/conf.d
    ports:
      - ${PORT_NGINX}:80
    networks:
      glavingo:
        aliases:
          - nginx.${DOMAIN_NAME}
      haproxy-external:
        aliases:
          - ${DOMAIN_NAME}.local

networks:
  glavingo:
    driver: bridge
  haproxy-external:
    external:
        name: haproxy-network
